[build]
  command = "npm run build"
  publish = "build"   # <-- CRA output ke 'build', bukan 'dist'

[build.environment]
  NODE_VERSION = "20"
  # Pilihan darurat jika masih ada lint warning:
  # CI = "false"
  # DISABLE_ESLINT_PLUGIN = "true"
